# This file is a template, and might need editing before it works on your project.
# Using job token: https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#job-token

stages:
  - build

# Templace for the job definition
.job_template: &job_definition  # Hidden key that defines an anchor named 'job_definition'
  # Official docker image.
  image: docker:latest
  timeout: 4 hours
  stage: build
  # variables:
  #   GIT_STRATEGY: clone
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Build for multiple eventAnalysis versions
  parallel:
    matrix:
      - ANALYSIS_READER_VERSION:
          - prod6T
          - prod6Y
          - prod7_V07

# Build the master branch when there is no tag
docker-build-master:
  <<: *job_definition
  script:
    - docker build --pull --build-arg HIGHLANDPILOT_IMAGE_VERSION=${CI_HIGHLANDPILOT_VERSION} --build-arg VERSION_ARG=master --build-arg ANALYSIS_READER_VERSION=${ANALYSIS_READER_VERSION} --build-arg GIT_T2K_TOKEN=$CI_REGISTRY_PASSWORD --build-arg GIT_T2K_USERNAME=$CI_REGISTRY_USER -t "$CI_REGISTRY_IMAGE:$ANALYSIS_READER_VERSION-master" .
    - docker push "$CI_REGISTRY_IMAGE:$ANALYSIS_READER_VERSION-master"
  only:
    - master

# Additional build when a tag is made (required an additional build step on top of the master build)
docker-build-tags:
  <<: *job_definition
  script:
    - docker build --pull --build-arg HIGHLANDPILOT_IMAGE_VERSION=${CI_HIGHLANDPILOT_VERSION} --build-arg VERSION_ARG=$CI_COMMIT_TAG --build-arg ANALYSIS_READER_VERSION=${ANALYSIS_READER_VERSION} --build-arg GIT_T2K_TOKEN=$CI_REGISTRY_PASSWORD --build-arg GIT_T2K_USERNAME=$CI_REGISTRY_USER -t "$CI_REGISTRY_IMAGE:$ANALYSIS_READER_VERSION-$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$ANALYSIS_READER_VERSION-$CI_COMMIT_TAG"
    # Also publish the tagged version as "latest"
    - docker tag "$CI_REGISTRY_IMAGE:$ANALYSIS_READER_VERSION-$CI_COMMIT_TAG" "$CI_REGISTRY_IMAGE:$ANALYSIS_READER_VERSION-latest"
    - docker push "$CI_REGISTRY_IMAGE:$ANALYSIS_READER_VERSION-latest"

  only:
    - tags

# Steps for the merge request: no push to registry
docker-build-mr:
  <<: *job_definition
  script:
    - docker build --pull --build-arg HIGHLANDPILOT_IMAGE_VERSION=${CI_HIGHLANDPILOT_VERSION} --build-arg VERSION_ARG=2.81 --build-arg ANALYSIS_READER_VERSION=${ANALYSIS_READER_VERSION} --build-arg GIT_T2K_TOKEN=$CI_REGISTRY_PASSWORD --build-arg GIT_T2K_USERNAME=$CI_REGISTRY_USER -t "$CI_REGISTRY_IMAGE:$ANALYSIS_READER_VERSION-$CI_COMMIT_REF_SLUG" .
  only:
    - merge_requests

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_HOST: tcp://docker:2375
