//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Sep 15 17:37:36 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/oa_nt_beam_80730000-0000_ngg4oj3wpuhl_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TP0DECALReconModule__TP0DECALReconShower_h
#define ND__TP0DECALReconModule__TP0DECALReconShower_h
namespace ND {
namespace TP0DECALReconModule {
class TP0DECALReconShower;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TVector3.h"
#include "TLorentzVector.h"
#include "Riostream.h"
#include <string>

namespace ND {
namespace TP0DECALReconModule {
class TP0DECALReconShower : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UInt_t      UniqueID;    //
   TVector3    ConeAngle;    //
   TVector3    Direction;    //
   double      EDeposit;     //
   int         NDOF;         //
   TLorentzVector Position;     //
   double         Quality;      //
   double         AMR;          //
   double         CWTrackWidth;    //
   double         Max_Ratio;       //
   double         NormChargeSD;    //
   double         PathChargeRatio;    //
   double         TrShval;            //
   int            NHits;              //
   TVector3       BenCWPosition;      //
   int            StackNo;            //
   int            TrueID;             //
   string         Module;             //

   TP0DECALReconShower();
   TP0DECALReconShower(const TP0DECALReconShower & );
   virtual ~TP0DECALReconShower();

   ClassDef(TP0DECALReconShower,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
