//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Sep 15 17:37:36 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/oa_nt_beam_80730000-0000_ngg4oj3wpuhl_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTRExReconModule__TTPCAnaPattern_h
#define ND__TTRExReconModule__TTPCAnaPattern_h
namespace ND {
namespace TTRExReconModule {
class TTPCAnaPattern;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TClonesArray.h"

namespace ND {
namespace TTRExReconModule {
class TTPCAnaPattern : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Bool_t      S1Sflag;     ///< A flag to say whether this pattern would pass the TPC
   Int_t       PatternID;    ///< The ID of the pattern
   Int_t       NJunctions;    ///< The number of junctions in the pattern.
   TClonesArray* Junctions;     ///< The constituent junctions of the pattern
   Int_t         NPaths;        ///< The number of paths.
   TClonesArray* Paths;         ///< The constituent paths of the pattern.
   Int_t         TPC;           ///< The TPC in which the pattern resides.

   TTPCAnaPattern();
   TTPCAnaPattern(const TTPCAnaPattern & );
   virtual ~TTPCAnaPattern();

   ClassDef(TTPCAnaPattern,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
