//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Sep 15 17:37:36 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/oa_nt_beam_80730000-0000_ngg4oj3wpuhl_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerReconModule__TTrackerVertex_h
#define ND__TTrackerReconModule__TTrackerVertex_h
namespace ND {
namespace TTrackerReconModule {
class TTrackerVertex;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <string>

namespace ND {
namespace TTrackerReconModule {
class TTrackerVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    ///< The name of the algorithm that created this object.
   int         Status;           ///< The status for the fit.
   double      Quality;          ///< The quality of the fit. Ie. the Prob(chi2,ndof)
   int         NDOF;             ///< The number of degrees of freedom.

   TTrackerVertex();
   TTrackerVertex(const TTrackerVertex & );
   virtual ~TTrackerVertex();

   ClassDef(TTrackerVertex,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
