//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Sep 15 17:37:36 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/oa_nt_beam_80730000-0000_ngg4oj3wpuhl_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSmrdReconModule__TSmrdReconHit_h
#define ND__TSmrdReconModule__TSmrdReconHit_h
namespace ND {
namespace TSmrdReconModule {
class TSmrdReconHit;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TLorentzVector.h"

namespace ND {
namespace TSmrdReconModule {
class TSmrdReconHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //
   TLorentzVector PositionUncertainty;    //
   double         Charge;                 //
   double         dZ;                     //
   double         dT;                     //
   double         ContribCharge[2];       //
   int            Wall;                   //
   int            Yoke;                   //
   int            Layer;                  //
   int            Tower;                  //
   int            Counter;                //
   UInt_t         RMM;                    //
   UInt_t         TFB;                    //
   bool           IsInnerMatched;         //
   bool           IsUsed;                 //

   TSmrdReconHit();
   TSmrdReconHit(const TSmrdReconHit & );
   virtual ~TSmrdReconHit();

   ClassDef(TSmrdReconHit,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
