//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Sep 15 17:37:36 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/oa_nt_beam_80730000-0000_ngg4oj3wpuhl_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSmrdReconModule__TSmrdIsoTrack_h
#define ND__TSmrdReconModule__TSmrdIsoTrack_h
namespace ND {
namespace TSmrdReconModule {
class TSmrdIsoTrack;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"
#include "TVector3.h"

namespace ND {
namespace TSmrdReconModule {
class TSmrdIsoTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UInt_t      UniqueID;    //
   string      AlgorithmName;    ///<Name of the reconstruction algorithm.
   TLorentzVector FrontPos;         //
   TLorentzVector FrontPosVariance;    //
   TLorentzVector BackPos;             //
   TLorentzVector BackPosVariance;     //
   TVector3       Direction;           //
   TVector3       DirectionVariance;    //
   int            NHits;                //
   int            NNodes;               //
   int            Status;               //
   int            KalmanStatus;         //
   int            NDOF;                 //
   double         EDeposit;             //
   double         avgtime;              //
   double         Range;                //
   double         Chi2;                 //
   double         ThetaAngle;           //
   double         PhiAngle;             //
   TLorentzVector TrueInitPos;          //
   int            TrueInitDet;          //
   TLorentzVector TrueFinalPos;         //
   int            TrueFinalDet;         //
   TLorentzVector TrueInitMom;          //
   int            TrueId;               //
   int            TruePDG;              //
   int            TrueParentId;         //
   double         TrueHitPurity;        //
   double         TrueHitEff;           //

   TSmrdIsoTrack();
   TSmrdIsoTrack(const TSmrdIsoTrack & );
   virtual ~TSmrdIsoTrack();

   ClassDef(TSmrdIsoTrack,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
