//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Nov 25 13:45:36 2021 by ROOT version 5.34/34)
//      from the StreamerInfo in file /t2k/izmaylov/T2K_ND280_ANALYSIS/ANALYSIS/oaAnalysisReader/p7_V03_oa_nt_beam_90400128-0055_5dkklck5zqqj_anal_000_magnet201011airrun4-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TP0DReconModule__TP0DAlgoRes_h
#define ND__TP0DReconModule__TP0DAlgoRes_h
namespace ND {
namespace TP0DReconModule {
class TP0DAlgoRes;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <string>
#include <vector>

namespace ND {
namespace TP0DReconModule {
class TP0DAlgoRes : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //
   short       Cycle;            //The cycle number, based on the first hit.
   vector<short> Vertices;         //Holds internal Ids of Vertices pertinent to this algorithm result.
   vector<short> Particles;        //Holds internal Ids of Particles pertinent to this algorithm result.
   vector<short> Tracks;           //Holds internal Ids of Tracks pertinent to this algorithm result.
   vector<short> Showers;          //Holds internal Ids of Showers pertinent to this algorithm result.
   vector<short> Clusters;         //Holds internal Ids of Clusters pertinent to this algorithm result.
   vector<short> Nodes;            //Holds internal Ids of Nodes pertinent to this algorithm result.
   vector<short> Hits;             //Holds internal Ids of Hits pertinent to this algorithm result.
   short         NHits;            //A count of the Hits associated with this object.
   unsigned int  UniqueID;         //UNUSED: A unique ID used for reconstruction objects.
   string        FullName;         //The name of the p0dRecon algorithm that corresponds to this
   vector<short> AlgoResults;      //Holds internal Ids of daughter algorithm results to this one.
   short         Parent;           //The internal Id of the parent algorithm result of this one.
   short         UsedHitCluster;    //The internal Id of the cluster of hits which were used in a
   short         UnusedHitCluster;    //The internal Id of the cluster of hits which were not used in a

   TP0DAlgoRes();
   TP0DAlgoRes(const TP0DAlgoRes & );
   virtual ~TP0DAlgoRes();

   ClassDef(TP0DAlgoRes,6); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
