//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Nov 25 13:45:37 2021 by ROOT version 5.34/34)
//      from the StreamerInfo in file /t2k/izmaylov/T2K_ND280_ANALYSIS/ANALYSIS/oaAnalysisReader/p7_V03_oa_nt_beam_90400128-0055_5dkklck5zqqj_anal_000_magnet201011airrun4-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTruthTrajectoriesModule__TTruthTrajectory_h
#define ND__TTruthTrajectoriesModule__TTruthTrajectory_h
namespace ND {
namespace TTruthTrajectoriesModule {
class TTruthTrajectory;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"
#include <vector>
#include "ND__TTruthTrajectoriesModule__TTruthTrajectoryPoint.h"
#include "TVector3.h"

namespace ND {
namespace TTruthTrajectoriesModule {
class TTruthTrajectory : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         ID;          //
   int         PDG;         //
   string      Name;        //
   int         Category;    //
   TLorentzVector InitMomentum;    //
   TLorentzVector InitPosition;    //
   TLorentzVector FinalPosition;    //
   int            ParentID;         //
   int            PrimaryID;        //
   double         Mass;             //
   int            Charge;           //
   vector<ND::TTruthTrajectoriesModule::TTruthTrajectoryPoint> Points;           //The trajectory points where interactions occured along the  trajectory.
   vector<int>                                                 TraceSubdetectors;    //
   vector<bool>                                                TraceInActive;        //
   vector<TLorentzVector>                                      TraceEntrancePosition;    //
   vector<TLorentzVector>                                      TraceExitPosition;        //
   vector<TVector3>                                            TraceEntranceMomentum;    //
   vector<TVector3>                                            TraceExitMomentum;        //

   TTruthTrajectory();
   TTruthTrajectory(const TTruthTrajectory & );
   virtual ~TTruthTrajectory();

   ClassDef(TTruthTrajectory,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
