//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Nov 25 13:45:36 2021 by ROOT version 5.34/34)
//      from the StreamerInfo in file /t2k/izmaylov/T2K_ND280_ANALYSIS/ANALYSIS/oaAnalysisReader/p7_V03_oa_nt_beam_90400128-0055_5dkklck5zqqj_anal_000_magnet201011airrun4-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALReconModule__TECALReconTrack_h
#define ND__TTrackerECALReconModule__TECALReconTrack_h
namespace ND {
namespace TTrackerECALReconModule {
class TECALReconTrack;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TVector3.h"
#include "TLorentzVector.h"

namespace ND {
namespace TTrackerECALReconModule {
class TECALReconTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    Direction;    //The track direction
   double      EDeposit;     //The charge deposited by the track in units of MIPs
   TLorentzVector Position;     //The track starting 4-position.
   TLorentzVector PositionVar;    //The track starting 4-position variance.
   TLorentzVector BackPosition;    //The position of the end of the track

   TECALReconTrack();
   TECALReconTrack(const TECALReconTrack & );
   virtual ~TECALReconTrack();

   ClassDef(TECALReconTrack,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
