//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Nov 25 13:45:37 2021 by ROOT version 5.34/34)
//      from the StreamerInfo in file /t2k/izmaylov/T2K_ND280_ANALYSIS/ANALYSIS/oaAnalysisReader/p7_V03_oa_nt_beam_90400128-0055_5dkklck5zqqj_anal_000_magnet201011airrun4-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TP0DReconModule__TP0DHit_h
#define ND__TP0DReconModule__TP0DHit_h
namespace ND {
namespace TP0DReconModule {
class TP0DHit;
} // end of namespace.
} // end of namespace.

#include "TObject.h"

namespace ND {
namespace TP0DReconModule {
class TP0DHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int GeomID;      //Geometry Id of the TSingleHit.
   unsigned int ChanID;      //Channel Id of the TSingleHit.
   float        Charge;      //Reconstructed hit charge without attenuation correction from the  corresponding TSingleHit.
   float        Time;        //Reconstructed hit time from the corresponding TSingleHit.

   TP0DHit();
   TP0DHit(const TP0DHit & );
   virtual ~TP0DHit();

   ClassDef(TP0DHit,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
