//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jan 11 14:01:37 2023 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_90810096-0055_quxcl5i7qxq4_anal_000_magnet201508waterrun8-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisHeaderModuleBase_h
#define ND__TAnalysisHeaderModuleBase_h
namespace ND {
class TAnalysisHeaderModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisHeaderModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisHeaderModuleBase();
   TAnalysisHeaderModuleBase(const TAnalysisHeaderModuleBase & );
   virtual ~TAnalysisHeaderModuleBase();

   ClassDef(TAnalysisHeaderModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
