#ifndef ANATOOLS_FILE_VERSION
#define ANATOOLS_FILE_VERSION v11r31p67
#define ANATOOLS_FILE_MAJOR_VERSION 11
#define ANATOOLS_FILE_MINOR_VERSION 31
#define ANATOOLS_FILE_PATCH_VERSION 67
#define BEFORE_ANATOOLS_FILE(v,r,p) ((ANATOOLS_FILE_MAJOR_VERSION==(v)&&ANATOOLS_FILE_MINOR_VERSION==(r)&&ANATOOLS_FILE_PATCH_VERSION<(p))||(ANATOOLS_FILE_MAJOR_VERSION==(v)&&ANATOOLS_FILE_MINOR_VERSION<(r))||(ANATOOLS_FILE_MAJOR_VERSION<(v)))
#define EQUALS_ANATOOLS_FILE(v,r,p) (ANATOOLS_FILE_MAJOR_VERSION==(v)&&ANATOOLS_FILE_MINOR_VERSION==(r)&&ANATOOLS_FILE_PATCH_VERSION==(p))
#endif
