//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Nov  8 13:36:45 2016 by ROOT version 5.34/34)
//      from the StreamerInfo in file /hep/T2K/DataDir/valid/oa_nt_beam_90410000-0002_g6rrt6tsqxr2_anal_000_prod005magnet201011waterc-bsdv01.root
//////////////////////////////////////////////////////////


#ifndef ND__TSHAHashValue_h
#define ND__TSHAHashValue_h
namespace ND {
class TSHAHashValue;
} // end of namespace.

#include "TNamed.h"

namespace ND {
class TSHAHashValue {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fHash[5];    //

   TSHAHashValue();
   TSHAHashValue(const TSHAHashValue & );
   virtual ~TSHAHashValue();

};
} // namespace
#endif
