//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Nov  8 13:36:45 2016 by ROOT version 5.34/34)
//      from the StreamerInfo in file /hep/T2K/DataDir/valid/oa_nt_beam_90410000-0002_g6rrt6tsqxr2_anal_000_prod005magnet201011waterc-bsdv01.root
//////////////////////////////////////////////////////////


#ifndef ND__TGRooTrackerVtxModule_h
#define ND__TGRooTrackerVtxModule_h
namespace ND {
class TGRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TGRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TGRooTrackerVtxModule();
   TGRooTrackerVtxModule(const TGRooTrackerVtxModule & );
   virtual ~TGRooTrackerVtxModule();

   ClassDef(TGRooTrackerVtxModule,2); // Generated by MakeProject.
};
} // namespace
#endif
