//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Nov 17 16:54:42 2016 by ROOT version 5.34/34)
//      from the StreamerInfo in file /hep/T2K/DataDir/PROD6/oa_nd_spl_00011000-0000_4stg6pqnornm_anal_001_v11r31p5-wg-bugaboo-bsdv01_2_prod6G.root
//////////////////////////////////////////////////////////


#ifndef ND__TRooTrackerVtxModuleBase_h
#define ND__TRooTrackerVtxModuleBase_h
namespace ND {
class TRooTrackerVtxModuleBase;
} // end of namespace.

#include "ND__TAnalysisTruthModuleBase.h"
#include "TClonesArray.h"

namespace ND {
class TRooTrackerVtxModuleBase : public ND::TAnalysisTruthModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       fNVtx;       ///< The number of vertices
   TClonesArray* fVtx;        ///< TClonesArray of vertex objects 
   bool          fPassThroughPresent;    //

   TRooTrackerVtxModuleBase();
   TRooTrackerVtxModuleBase(const TRooTrackerVtxModuleBase & );
   virtual ~TRooTrackerVtxModuleBase();

   ClassDef(TRooTrackerVtxModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
