//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Nov 17 16:54:42 2016 by ROOT version 5.34/34)
//      from the StreamerInfo in file /hep/T2K/DataDir/PROD6/oa_nd_spl_00011000-0000_4stg6pqnornm_anal_001_v11r31p5-wg-bugaboo-bsdv01_2_prod6G.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALPi0ReconModule_h
#define ND__TTrackerECALPi0ReconModule_h
namespace ND {
class TTrackerECALPi0ReconModule;
} // end of namespace.

#include "ND__TAnalysisReconModuleBase.h"

namespace ND {
class TTrackerECALPi0ReconModule : public ND::TAnalysisReconModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TTrackerECALPi0ReconModule();
   TTrackerECALPi0ReconModule(const TTrackerECALPi0ReconModule & );
   virtual ~TTrackerECALPi0ReconModule();

   ClassDef(TTrackerECALPi0ReconModule,2); // Generated by MakeProject.
};
} // namespace
#endif
