//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Sep  4 09:00:22 2018 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/7B_new_iteration/oa_nt_beam_90400000-0000_jrvqx3jehzgh_anal_000_prod6amagnet201011airc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGeometrySummaryModule__TDetectorBoundingBox_h
#define ND__TGeometrySummaryModule__TDetectorBoundingBox_h
namespace ND {
namespace TGeometrySummaryModule {
class TDetectorBoundingBox;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TVector3.h"

namespace ND {
namespace TGeometrySummaryModule {
class TDetectorBoundingBox : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    Minimum;     //
   TVector3    Maximum;     //

   TDetectorBoundingBox();
   TDetectorBoundingBox(const TDetectorBoundingBox & );
   virtual ~TDetectorBoundingBox();

   ClassDef(TDetectorBoundingBox,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
