//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Sep  4 09:00:22 2018 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/7B_new_iteration/oa_nt_beam_90400000-0000_jrvqx3jehzgh_anal_000_prod6amagnet201011airc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TData_h
#define ND__TData_h
namespace ND {
class TData;
} // end of namespace.

#include "ND__TDatum.h"

namespace ND {
class TData : public ND::TDatum {

public:
// Nested classes declaration.

public:
// Data Members.

   TData();
   TData(const TData & );
   virtual ~TData();

   ClassDef(TData,4); // Generated by MakeProject.
};
} // namespace
#endif
