//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Sep  4 09:00:22 2018 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/7B_new_iteration/oa_nt_beam_90400000-0000_jrvqx3jehzgh_anal_000_prod6amagnet201011airc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TOutermostHits_h
#define ND__TGlobalReconModule__TOutermostHits_h
namespace ND {
namespace TGlobalReconModule {
class TOutermostHits;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "ND__TGlobalReconModule__TGlobalHit.h"

namespace ND {
namespace TGlobalReconModule {
class TOutermostHits : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   ND::TGlobalReconModule::TGlobalHit hitMinX;     ///< Hit with lowest X position.
   ND::TGlobalReconModule::TGlobalHit hitMaxX;     ///< Hit with highest X position.
   ND::TGlobalReconModule::TGlobalHit hitMinY;     ///< Hit with lowest Y position.
   ND::TGlobalReconModule::TGlobalHit hitMaxY;     ///< Hit with highest Y position.
   ND::TGlobalReconModule::TGlobalHit hitMinZ;     ///< Hit with lowest Z position.
   ND::TGlobalReconModule::TGlobalHit hitMaxZ;     ///< Hit with highest Z position.

   TOutermostHits();
   TOutermostHits(const TOutermostHits & );
   virtual ~TOutermostHits();

   ClassDef(TOutermostHits,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
