//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Sep  4 09:00:22 2018 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod7/7B_new_iteration/oa_nt_beam_90400000-0000_jrvqx3jehzgh_anal_000_prod6amagnet201011airc-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALReconModule__TECALReconTrack_h
#define ND__TTrackerECALReconModule__TECALReconTrack_h
namespace ND {
namespace TTrackerECALReconModule {
class TECALReconTrack;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TVector3.h"
#include "TLorentzVector.h"

namespace ND {
namespace TTrackerECALReconModule {
class TECALReconTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    Direction;    ///< The track direction
   double      EDeposit;     ///< The charge deposited by the track in units of MIPs
   TLorentzVector Position;     ///< The track starting 4-position.
   TLorentzVector PositionVar;    ///< The track starting 4-position variance.
   TLorentzVector BackPosition;    ///< The position of the end of the track

   TECALReconTrack();
   TECALReconTrack(const TECALReconTrack & );
   virtual ~TECALReconTrack();

   ClassDef(TECALReconTrack,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
