//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Nov 17 16:53:10 2016 by ROOT version 5.34/34)
//      from the StreamerInfo in file /hep/T2K/DataDir/PROD6/oa_nd_spl_00011000-0000_4stgpe5m7bc7_anal_000_v11r31p5-wg-bugaboo-bsdv01_2_prod6E.root
//////////////////////////////////////////////////////////


#ifndef ND__TBasicDataQualityModule_h
#define ND__TBasicDataQualityModule_h
namespace ND {
class TBasicDataQualityModule;
} // end of namespace.

#include "ND__TAnalysisHeaderModuleBase.h"

namespace ND {
class TBasicDataQualityModule : public ND::TAnalysisHeaderModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TBasicDataQualityModule();
   TBasicDataQualityModule(const TBasicDataQualityModule & );
   virtual ~TBasicDataQualityModule();

   ClassDef(TBasicDataQualityModule,2); // Generated by MakeProject.
};
} // namespace
#endif
