# This file is a template, and might need editing before it works on your project.
# Using job token: https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#job-token

########################@

image: docker:latest
services:
- docker:dind

stages:
  - build
  - release

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

# Templace for the job definition
.job_template: &job_definition  # Hidden key that defines an anchor named 'job_definition'
  # Official docker image.
  stage: build
  script:
    - docker build --pull --build-arg SOFTPILOT_IMAGE_VERSION=centos7-${CI_ND280PILOT_VERSION} --build-arg GIT_T2K_TOKEN=$CI_REGISTRY_PASSWORD --build-arg GIT_T2K_USERNAME=$CI_REGISTRY_USER -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

# Build the master branch when there is no tag
docker-build-master:
  <<: *job_definition
  only:
    - master
# Build the master branch when there is no tag
docker-build-stable:
  <<: *job_definition
  only:
    - stable
# Additional build when a tag is made
docker-build-tags:
  <<: *job_definition
  only:
    - tags

# Steps for the merge request
docker-build-mr:
  <<: *job_definition
  only:
    - merge_requests

release-master:
  stage: release
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

release-stable:
  stage: release
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:stable"
    - docker push "$CI_REGISTRY_IMAGE:stable"
  only:
    - stable

release-tags:
  stage: release
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    - tags

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
