//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Apr  5 14:16:32 2023 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_80600124-0055_f72mofocwqdr_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSmrdReconModule__TSmrdReconHit_h
#define ND__TSmrdReconModule__TSmrdReconHit_h
namespace ND {
namespace TSmrdReconModule {
class TSmrdReconHit;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TLorentzVector.h"

namespace ND {
namespace TSmrdReconModule {
class TSmrdReconHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //The reconstructed 4-position of the corresponding double ended ND::THit.
   TLorentzVector PositionUncertainty;    //\brief  The uncertainty on the reconstructed 4-position of the corresponding double ended ND::THit.
   double         Charge;                 //The reconstructed charge of the corresponding double ended ND::THit.
   double         dZ;                     //\short The difference in Z between the combined ND::THit(double ended  bars)  and the first contributor ND::THit.
   double         dT;                     //\short The difference between the reconstructed ND::THit times between  the two contributors.
   double         ContribCharge[2];       //The reconstructed charges from each contributor of the double ended bar.
   int            Wall;                   //The SMRD wall in which this the corresponding ND::THit resides. Is assigned a value from TSmrdReconModule::ESMRDWall.  Uses ND::TSMRDGeom::IsSMRDTopWall, ND::TSMRDGeom::IsSMRDBotoomWall, ND::TSMRDGeom::IsSMRDLeftWall and ND::TSMRDGeom::IsSMRDRightWall.
   int            Yoke;                   //The SMRD yoke number. ranges from 1(most upstream) to 8(most downstream).
   int            Layer;                  //The SMRD ring number.  ranges from 1(most inner) to 6(most outer).
   int            Tower;                  //The SMRD tower number. Tower 1 is left-top and numbers are assigned clockwise.
   int            Counter;                //The SMRD scintillator number.  Each yoke has either 20-for vertical(SMRD Left/Right) walls, or 16 for  horizontal walls.
   unsigned int   RMM;                    //The RMM Id of the channel corresponding to the first contributor hit.
   unsigned int   TFB;                    //The TFB Id of the channel corresponding to the first contributor hit.
   bool           IsInnerMatched;         //Designates if the corresponding ND::THit was matched
   bool           IsUsed;                 //Designates if the corresponding ND::THit was used in a  reconstructed object.

   TSmrdReconHit();
   TSmrdReconHit(const TSmrdReconHit & );
   virtual ~TSmrdReconHit();

   ClassDef(TSmrdReconHit,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
