//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Apr  5 14:16:33 2023 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_80600124-0055_f72mofocwqdr_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALReconModule__TECALReconTrack_h
#define ND__TTrackerECALReconModule__TECALReconTrack_h
namespace ND {
namespace TTrackerECALReconModule {
class TECALReconTrack;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TVector3.h"
#include "TLorentzVector.h"

namespace ND {
namespace TTrackerECALReconModule {
class TECALReconTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    Direction;    //The track direction
   double      EDeposit;     //The charge deposited by the track in units of MIPs
   TLorentzVector Position;     //The track starting 4-position.
   TLorentzVector PositionVar;    //The track starting 4-position variance.
   TLorentzVector BackPosition;    //The position of the end of the track

   TECALReconTrack();
   TECALReconTrack(const TECALReconTrack & );
   virtual ~TECALReconTrack();

   ClassDef(TECALReconTrack,3); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
