//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Apr  5 14:16:32 2023 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_80600124-0055_f72mofocwqdr_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__JNuBeamFlux_h
#define ND__JNuBeamFlux_h
namespace ND {
class JNuBeamFlux;
} // end of namespace.

#include "ND__RooTrackerVtxBase.h"
#include "TObjString.h"

namespace ND {
class JNuBeamFlux : public ND::RooTrackerVtxBase {

public:
// Nested classes declaration.

public:
// Data Members.
   long        NuFluxEntry;    //Corresponding entry in orig flux file
   TObjString* NuFileName;     //Original flux file name neutrino parent info
   int         NuParentPdg;    //Parent hadron pdg code
   int         NuParentDecMode;    //Parent hadron decay mode
   double      NuParentDecP4[4];    //Parent hadron 4-momentum at decay
   double      NuParentDecX4[4];    //Parent hadron 4-position at decay
   float       NuCospibm;           //Parent hadron cos(theta) relative to beam at decay
   float       NuNorm;              //Normalization weight
   double      NuParentProP4[4];    //Parent hadron 4-momentum at production
   double      NuParentProX4[4];    //Parent hadron 4-position at production
   float       NuCospi0bm;          //Parent hadron cos(theta) relative to beam at production
   float       NuRnu;               //Neutrino r position at ND5/6 plane
   float       NuXnu[2];            //Neutrino (x,y) position at ND5/6 plane
   int         NuIdfd;              //Detector ID primary particle information
   int         NuGipart;            //Primary particle ID
   float       NuGpos0[3];          //Primary particle starting point
   float       NuGvec0[3];          //Primary particle direction at starting point
   float       NuGamom0;            //Momentum of the primary particle at the starting point Interation History Information
   int         NuNg;                //Number of interaction steps
   float       NuGp[12][3];         //Momentum of ancestor particle
   float       NuGcosbm[12];        //Ancestor particle cos(theta) relative to beam
   float       NuGv[12][3];         //Position of ancestor particle
   int         NuGpid[12];          //PDG ancestor particle ID
   int         NuGmec[12];          //Particle production mechanism of ancestor particle Normalization and Transfer Matrix Information
   float       NuEnusk;             //Neutrino Energy at SK
   float       NuNormsk;            //Normalization weight at SK
   float       NuAnorm;             //ND Acceptance Weight Out-of-target Secondary Interactions
   int         NuGmat[12];          //Material in which the particle originates
   float       NuGdistc[12];        //Distance traveled through carbon
   float       NuGdistal[12];       //Distance traveled through aluminum
   float       NuGdistti[12];       //Distance traveled through titanium
   float       NuGdistfe[12];       //Distance traveled through iron Beam parameter information
   float       NuVersion;           //Jnubeam flux version
   int         NuTuneid;            //Beam tune ID #
   int         NuNtrig;             //Number of triggers
   int         NuPint;              //Interaction model ID
   float       NuBpos[2];           //Beam center position
   float       NuBtilt[2];          //Beam angle
   float       NuBrms[2];           //Beam RMS width
   float       NuEmit[2];           //Beam Emittance
   float       NuAlpha[2];          //Beam Alpha
   float       NuHcur[3];           //Horn currents
   int         NuRand;              //Random seed

   JNuBeamFlux();
   JNuBeamFlux(const JNuBeamFlux & );
   virtual ~JNuBeamFlux();

   ClassDef(JNuBeamFlux,2); // Generated by MakeProject.
};
} // namespace
#endif
