//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Apr  5 14:16:33 2023 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_80600124-0055_f72mofocwqdr_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerReconModule__TTrueParticle_h
#define ND__TTrackerReconModule__TTrueParticle_h
namespace ND {
namespace TTrackerReconModule {
class TTrueParticle;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "ND__TTrueVertex.h"

namespace ND {
namespace TTrackerReconModule {
class TTrueParticle : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         ID;          //Trajectoy  Id
   double      Pur;         //The purity for matching
   double      Eff;         //The efficiency for matching
   ND::TTrueVertex Vertex;      //True vertex associated to this TrueParticle

   TTrueParticle();
   TTrueParticle(const TTrueParticle & );
   virtual ~TTrueParticle();

   ClassDef(TTrueParticle,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
