//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Nov  4 15:38:32 2016 by ROOT version 5.34/34)
//      from the StreamerInfo in file /hep/T2K/DataDir/valid/oa_nt_beam_90210042-0030_bbzjto7xz4zh_anal_000_prod6amagnet201011waterb-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisTruthModuleBase_h
#define ND__TAnalysisTruthModuleBase_h
namespace ND {
class TAnalysisTruthModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisTruthModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisTruthModuleBase();
   TAnalysisTruthModuleBase(const TAnalysisTruthModuleBase & );
   virtual ~TAnalysisTruthModuleBase();

   ClassDef(TAnalysisTruthModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
