//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Nov  4 11:44:16 2016 by ROOT version 5.34/34)
//      from the StreamerInfo in file /hep/T2K/DataDir/valid/oa_nt_beam_90410000-0000_h252u2jujozw_anal_000_prod005magnet201011waterc-bsdv01.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisModuleBase_h
#define ND__TAnalysisModuleBase_h
namespace ND {
class TAnalysisModuleBase;
} // end of namespace.

#include "TNamed.h"
#include "TTree.h"
#include "Riostream.h"
#include <string>

namespace ND {
class TAnalysisModuleBase : public TNamed {

public:
// Nested classes declaration.

public:
// Data Members.
   Bool_t      fIsEnabled;    //
   Bool_t      fIsUsedForPreselection;    //
   TTree*      fOutputTree;               //
   Int_t       fBufferSize;               //
   Int_t       fSplitLevel;               //
   string      fDescription;              //
   string      fCVSTagName;               //
   string      fCVSID;                    //
   Int_t       fRunID;                    //
   Int_t       fSubrunID;                 //
   Int_t       fEventID;                  //
   Int_t       fPreselected;              //
   string      fInputDirectory;           //

   TAnalysisModuleBase();
   TAnalysisModuleBase(const TAnalysisModuleBase & );
   virtual ~TAnalysisModuleBase();

   ClassDef(TAnalysisModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
