# This file is a template, and might need editing before it works on your project.
# Using job token: https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#job-token

########################@

image: docker:latest
services:
- docker:dind

stages:
  - build
  - test
  # - release

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

# Templace for the build definition
.build_template: &build_definition  # Hidden key that defines an anchor named 'job_definition'
  # Official docker image.
  stage: build
  script:
    - docker build --pull --build-arg DOCKERBASE_VERSION=$CI_DOCKERBASE_VERSION --build-arg DOCKERBASE_FLAVOR=${VAR_OS_FLAVOR} --build-arg GIT_T2K_TOKEN=$CI_REGISTRY_PASSWORD --build-arg GIT_T2K_USERNAME=$CI_REGISTRY_USER -t "$CI_REGISTRY_IMAGE:${VAR_OS_FLAVOR}-${OUTPUT_TAG}" .
    - docker push "$CI_REGISTRY_IMAGE:${VAR_OS_FLAVOR}-$OUTPUT_TAG"

# Templace for the test definition
.test_template: &test_definition  # Hidden key that defines an anchor named 'test_definition'
  stage: test
  script:
    - docker pull "$CI_REGISTRY_IMAGE:${VAR_OS_FLAVOR}-$IMAGE_TAG"
    - docker run "$CI_REGISTRY_IMAGE:${VAR_OS_FLAVOR}-$IMAGE_TAG" ./tests/test.sh $CI_REGISTRY_USER $CI_REGISTRY_PASSWORD

# Templace for the test definition
# .release_template: &release_definition  # Hidden key that defines an anchor named 'test_definition'
#   stage: release
#   script:
#     - docker pull "$CI_REGISTRY_IMAGE:${VAR_OS_FLAVOR}-$OUT_VERSION"
    # - docker tag "$CI_REGISTRY_IMAGE:${VAR_OS_FLAVOR}-$OUT_VERSION" "$CI_REGISTRY_IMAGE:${VAR_OS_FLAVOR}-${OUT_VERSION}"
    # - docker push "$CI_REGISTRY_IMAGE:${VAR_OS_FLAVOR}-${OUT_VERSION}"

######################
##### CENTOS-7 #######
######################

####### Build
# Build the master branch when there is no tag
docker-build-centos7-master:
  <<: *build_definition
  only:
    - master
  variables:
    VAR_OS_FLAVOR: centos7
    OUTPUT_TAG: latest
# Build the master branch when there is no tag
docker-build-centos7-stable:
  <<: *build_definition
  only:
    - stable
  variables:
    VAR_OS_FLAVOR: centos7
    OUTPUT_TAG: stable
# Additional build when a tag is made
docker-build-centos7-tags:
  <<: *build_definition
  only:
    - tags
  variables:
    VAR_OS_FLAVOR: centos7
    OUTPUT_TAG: $CI_COMMIT_TAG
# Build for the merge request
docker-build-centos7-mr:
  <<: *build_definition
  only:
    - merge_requests
  variables:
    VAR_OS_FLAVOR: centos7
    OUTPUT_TAG: $CI_COMMIT_REF_SLUG

####### Test
test-centos7:
  <<: *test_definition
  only:
    - merge_requests
  variables:
    VAR_OS_FLAVOR: centos7
    IMAGE_TAG: $CI_COMMIT_REF_SLUG

####### Release
# release-centos7-master:
#   <<: *release_definition
#   only:
#     - master
#   variables:
#     VAR_OS_FLAVOR: centos7
#     OUTPUT_TAG: latest
# release-centos7-stable:
#   <<: *release_definition
#   only:
#     - stable
#   variables:
#     VAR_OS_FLAVOR: centos7
#     OUTPUT_TAG: stable
# release-centos7-tags:
#   <<: *release_definition
#   only:
#     - tags
#   variables:
#     VAR_OS_FLAVOR: centos7
#     OUTPUT_TAG: $CI_COMMIT_TAG


######################
##### Buster #######
######################

####### Build
# Build the master branch when there is no tag
docker-build-buster-master:
  <<: *build_definition
  only:
    - master
  variables:
    VAR_OS_FLAVOR: buster
    OUTPUT_TAG: latest
# Build the master branch when there is no tag
docker-build-buster-stable:
  <<: *build_definition
  only:
    - stable
  variables:
    VAR_OS_FLAVOR: buster
    OUTPUT_TAG: stable
# Additional build when a tag is made
docker-build-buster-tags:
  <<: *build_definition
  only:
    - tags
  variables:
    VAR_OS_FLAVOR: buster
    OUTPUT_TAG: $CI_COMMIT_TAG
# Build for the merge request
docker-build-buster-mr:
  <<: *build_definition
  only:
    - merge_requests
  variables:
    VAR_OS_FLAVOR: buster
    OUTPUT_TAG: $CI_COMMIT_REF_SLUG

####### Test
test-buster:
  <<: *test_definition
  only:
    - merge_requests
  variables:
    VAR_OS_FLAVOR: buster
    IMAGE_TAG: $CI_COMMIT_REF_SLUG

####### Release
# release-buster-master:
#   <<: *release_definition
#   only:
#     - master
#   variables:
#     VAR_OS_FLAVOR: buster
#     OUTPUT_TAG: latest
# release-buster-stable:
#   <<: *release_definition
#   only:
#     - stable
#   variables:
#     VAR_OS_FLAVOR: buster
#     OUTPUT_TAG: stable
# release-buster-tags:
#   <<: *release_definition
#   only:
#     - tags
#   variables:
#     VAR_OS_FLAVOR: buster
#     OUTPUT_TAG: $CI_COMMIT_TAG

# release-centos7-master:
#   stage: release
#   script:
#     - docker pull "$CI_REGISTRY_IMAGE:centos7-$CI_COMMIT_REF_SLUG"
#     - docker tag "$CI_REGISTRY_IMAGE:centos7-$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:centos7-latest"
#     - docker push "$CI_REGISTRY_IMAGE:centos7-latest"
#   only:
#     - master

# release-centos7-stable:
#   stage: release
#   script:
#     - docker pull "$CI_REGISTRY_IMAGE:centos7-$CI_COMMIT_REF_SLUG"
#     - docker tag "$CI_REGISTRY_IMAGE:centos7-$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:centos7-stable"
#     - docker push "$CI_REGISTRY_IMAGE:centos7-stable"
#   only:
#     - stable

# release-centos7-tags:
#   stage: release
#   script:
#     - docker pull "$CI_REGISTRY_IMAGE:centos7-$CI_COMMIT_REF_SLUG"
#     - docker tag "$CI_REGISTRY_IMAGE:centos7-$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:centos7-$CI_COMMIT_TAG"
#     - docker push "$CI_REGISTRY_IMAGE:centos7-$CI_COMMIT_TAG"
#   only:
#     - tags

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_HOST: tcp://docker:2375
