//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jan 11 14:09:42 2023 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_80710119-0055_df7igapcoooo_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TTrackerObject_h
#define ND__TGlobalReconModule__TTrackerObject_h
namespace ND {
namespace TGlobalReconModule {
class TTrackerObject;
} // end of namespace.
} // end of namespace.

#include "ND__TSubBaseObject.h"

namespace ND {
namespace TGlobalReconModule {
class TTrackerObject : public ND::TSubBaseObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      Charge;      //
   int         matchingFailure_flag;    //

   TTrackerObject();
   TTrackerObject(const TTrackerObject & );
   virtual ~TTrackerObject();

   ClassDef(TTrackerObject,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
