//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jul 15 18:05:54 2022 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_90400000-0000_2sxl5m3goua7_anal_000_magnet201011airrun4-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__RooTrackerVtxBase_h
#define ND__RooTrackerVtxBase_h
namespace ND {
class RooTrackerVtxBase;
} // end of namespace.

#include "TObject.h"

namespace ND {
class RooTrackerVtxBase : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.

   RooTrackerVtxBase();
   RooTrackerVtxBase(const RooTrackerVtxBase & );
   virtual ~RooTrackerVtxBase();

   ClassDef(RooTrackerVtxBase,2); // Generated by MakeProject.
};
} // namespace
#endif
