/********************************************************************
* /home/t2k/aspeers/Highland_Installs/HighLAND_2.89/highlandCore_2.46/Linux-CentOS_7-gcc_4.8-x86_64/dict/G_CategoryClasses.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/t2k/aspeers/Highland_Installs/HighLAND_2.89/highlandCore_2.46/Linux-CentOS_7-gcc_4.8-x86_64/dict/G_CategoryClasses.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG_CategoryClasses();
extern void G__cpp_setup_inheritanceG_CategoryClasses();
extern void G__cpp_setup_typetableG_CategoryClasses();
extern void G__cpp_setup_memvarG_CategoryClasses();
extern void G__cpp_setup_globalG_CategoryClasses();
extern void G__cpp_setup_memfuncG_CategoryClasses();
extern void G__cpp_setup_funcG_CategoryClasses();
extern void G__set_cpp_environmentG_CategoryClasses();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/t2k/aspeers/Highland_Installs/HighLAND_2.89/highlandCore_2.46/inc/CategoryClasses.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G_CategoryClassesLN_TClass;
extern G__linked_taginfo G__G_CategoryClassesLN_TBuffer;
extern G__linked_taginfo G__G_CategoryClassesLN_TMemberInspector;
extern G__linked_taginfo G__G_CategoryClassesLN_TObject;
extern G__linked_taginfo G__G_CategoryClassesLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__G_CategoryClassesLN_string;
extern G__linked_taginfo G__G_CategoryClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G_CategoryClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G_CategoryClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G_CategoryClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G_CategoryClassesLN_TrackTypeDefinition;
extern G__linked_taginfo G__G_CategoryClassesLN_TrackCategoryDefinition;
extern G__linked_taginfo G__G_CategoryClassesLN_vectorlETrackTypeDefinitioncOallocatorlETrackTypeDefinitiongRsPgR;
extern G__linked_taginfo G__G_CategoryClassesLN_reverse_iteratorlEvectorlETrackTypeDefinitioncOallocatorlETrackTypeDefinitiongRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
