//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Sep  5 15:48:12 2019 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod6T/oa_nt_beam_90210000-0000_mghj7aenjmue_anal_000_magnet201011waterrun2-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__RooTrackerVtxBase_h
#define ND__RooTrackerVtxBase_h
namespace ND {
class RooTrackerVtxBase;
} // end of namespace.

#include "TObject.h"

namespace ND {
class RooTrackerVtxBase : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.

   RooTrackerVtxBase();
   RooTrackerVtxBase(const RooTrackerVtxBase & );
   virtual ~RooTrackerVtxBase();

   ClassDef(RooTrackerVtxBase,2); // Generated by MakeProject.
};
} // namespace
#endif
