//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Sep  5 15:48:12 2019 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod6T/oa_nt_beam_90210000-0000_mghj7aenjmue_anal_000_magnet201011waterrun2-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TNRooTrackerVtxModule_h
#define ND__TNRooTrackerVtxModule_h
namespace ND {
class TNRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TNRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TNRooTrackerVtxModule();
   TNRooTrackerVtxModule(const TNRooTrackerVtxModule & );
   virtual ~TNRooTrackerVtxModule();

   ClassDef(TNRooTrackerVtxModule,2); // Generated by MakeProject.
};
} // namespace
#endif
