//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Sep  5 15:48:12 2019 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod6T/oa_nt_beam_90210000-0000_mghj7aenjmue_anal_000_magnet201011waterrun2-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TRooTrackerVtxModuleBase_h
#define ND__TRooTrackerVtxModuleBase_h
namespace ND {
class TRooTrackerVtxModuleBase;
} // end of namespace.

#include "ND__TAnalysisTruthModuleBase.h"
#include "TClonesArray.h"

namespace ND {
class TRooTrackerVtxModuleBase : public ND::TAnalysisTruthModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       fNVtx;       ///< The number of vertices
   TClonesArray* fVtx;        ///< TClonesArray of vertex objects 
   bool          fPassThroughPresent;    //

   TRooTrackerVtxModuleBase();
   TRooTrackerVtxModuleBase(const TRooTrackerVtxModuleBase & );
   virtual ~TRooTrackerVtxModuleBase();

   ClassDef(TRooTrackerVtxModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
