#!/bin/bash
#
# Make sure the repository is configured to track all of the upstream
# branches.  

usage () {
  cat <<EOF
Usage: nd280-track-upstream

  No arguments.  This is run in a local repository to set it up so
that it tracks all of the upstream branches.  These branches are all in
refs/remotes/origin.  This command can be run multiple times, and it's
a good idea to run it once in a while to make sure that your
.git/config is up to date.

EOF
}

if [ $# -gt 0 ]; then usage; exit 0; fi

for ref in `git rev-parse --symbolic --remotes=origin`; do
  r=$(echo $ref | sed 's%^refs/remotes/%%g' | sed 's%^origin/%%g')
  if ! git branch --set-upstream-to origin/$r $r; then
    git branch --set-upstream $r $ref
  fi
done

#-*-Shell-Script-*-
