//
// File generated by /t2k/Software/v12r25/ROOT/v5r34p34n00/Linux-x86_64//bin/rootcint at Thu Apr 20 02:12:47 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIhomedIt2kdIaspeersdIHighland_InstallsdIHighLAND_2dO89dIhighlandUtils_2dO46dILinuxmICentOS_7mIgcc_4dO8mIx86_64dIdictdIG_TTruthUtils
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G_TTruthUtils.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::TTruthUtils TTruthUtils;
      #else
      class TTruthUtils  {
         public:
         //friend XX;
         ::TClonesArray* fTrajectories; //
         ::TClonesArray* fVertices; //
         int* fNTrajectories; //
         int* fNVertices; //
         int verbosity; //
         bool fOrdered; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TTruthUtils_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void TTruthUtils_Dictionary();
   static void *new_TTruthUtils(void *p = 0);
   static void *newArray_TTruthUtils(Long_t size, void *p);
   static void delete_TTruthUtils(void *p);
   static void deleteArray_TTruthUtils(void *p);
   static void destruct_TTruthUtils(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TTruthUtils*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::TTruthUtils) == sizeof( ::ROOTShadow::Shadow::TTruthUtils));
      ::TTruthUtils *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::TTruthUtils),0);
      static ::ROOT::TGenericClassInfo 
         instance("TTruthUtils", "/home/t2k/aspeers/Highland_Installs/HighLAND_2.89/highlandUtils_2.46/inc/TTruthUtils.hxx", 14,
                  typeid(::TTruthUtils), ::ROOT::DefineBehavior(ptr, ptr),
                  &TTruthUtils_ShowMembers, &TTruthUtils_Dictionary, isa_proxy, 4,
                  sizeof(::TTruthUtils) );
      instance.SetNew(&new_TTruthUtils);
      instance.SetNewArray(&newArray_TTruthUtils);
      instance.SetDelete(&delete_TTruthUtils);
      instance.SetDeleteArray(&deleteArray_TTruthUtils);
      instance.SetDestructor(&destruct_TTruthUtils);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TTruthUtils*)
   {
      return GenerateInitInstanceLocal((::TTruthUtils*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TTruthUtils*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void TTruthUtils_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::TTruthUtils*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void TTruthUtils_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class TTruthUtils.
      typedef ::ROOTShadow::Shadow::TTruthUtils ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::TTruthUtils*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTrajectories", &sobj->fTrajectories);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVertices", &sobj->fVertices);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fNTrajectories", &sobj->fNTrajectories);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fNVertices", &sobj->fNVertices);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "verbosity", &sobj->verbosity);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fOrdered", &sobj->fOrdered);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TTruthUtils(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TTruthUtils : new ::TTruthUtils;
   }
   static void *newArray_TTruthUtils(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TTruthUtils[nElements] : new ::TTruthUtils[nElements];
   }
   // Wrapper around operator delete
   static void delete_TTruthUtils(void *p) {
      delete ((::TTruthUtils*)p);
   }
   static void deleteArray_TTruthUtils(void *p) {
      delete [] ((::TTruthUtils*)p);
   }
   static void destruct_TTruthUtils(void *p) {
      typedef ::TTruthUtils current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::TTruthUtils

/********************************************************
* /home/t2k/aspeers/Highland_Installs/HighLAND_2.89/highlandUtils_2.46/Linux-CentOS_7-gcc_4.8-x86_64/dict/G_TTruthUtils.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG_TTruthUtils();

extern "C" void G__set_cpp_environmentG_TTruthUtils() {
  G__cpp_reset_tagtableG_TTruthUtils();
}
#include <new>
extern "C" int G__cpp_dllrevG_TTruthUtils() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TTruthUtils */
static int G__G_TTruthUtils_691_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TTruthUtils* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TTruthUtils(
(TClonesArray*) G__int(libp->para[0]), (TClonesArray*) G__int(libp->para[1])
, (Int_t*) G__int(libp->para[2]), (Int_t*) G__int(libp->para[3]));
   } else {
     p = new((void*) gvp) TTruthUtils(
(TClonesArray*) G__int(libp->para[0]), (TClonesArray*) G__int(libp->para[1])
, (Int_t*) G__int(libp->para[2]), (Int_t*) G__int(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TTruthUtils* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TTruthUtils[n];
     } else {
       p = new((void*) gvp) TTruthUtils[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TTruthUtils;
     } else {
       p = new((void*) gvp) TTruthUtils;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTruthUtils*) G__getstructoffset())->SetVerticesArray((TClonesArray*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTruthUtils*) G__getstructoffset())->SetVerticesNumber((Int_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTruthUtils*) G__getstructoffset())->SetTrajectoriesArray((TClonesArray*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTruthUtils*) G__getstructoffset())->SetTrajectoriesNumber((Int_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetTrajectoryById((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetParentTrajectory((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetParentTrajectory((ND::TTruthTrajectoriesModule::TTruthTrajectory*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetPrimaryParentTrajectory((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetPrimaryParentTrajectory((ND::TTruthTrajectoriesModule::TTruthTrajectory*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetMomentumSortedTrajectories();
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetTrajectoriesByCategory((int) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetTrajectoriesByName(*((string*) G__int(libp->para[0])));
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetTrajectoriesByPDG((Int_t) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetTrajectoriesByParent((Int_t) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetTrajectoriesByParent((ND::TTruthTrajectoriesModule::TTruthTrajectory*) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetTrajectoriesByPrimaryParent((Int_t) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetTrajectoriesByPrimaryParent((ND::TTruthTrajectoriesModule::TTruthTrajectory*) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>* pobj;
         const vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetTrajectoriesVector();
         pobj = new vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetVertexById((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetVertexOfTrajectory((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetVertexOfTrajectory((ND::TTruthTrajectoriesModule::TTruthTrajectory*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetVertexOfPrimaryTrajectory((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TTruthUtils*) G__getstructoffset())->GetVertexOfPrimaryTrajectory((ND::TTruthTrajectoriesModule::TTruthTrajectory*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthVerticesModule::TTruthVertex*>* pobj;
         const vector<ND::TTruthVerticesModule::TTruthVertex*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetVerticesByLocation(*(TVector3*) libp->para[0].ref, *(TVector3*) libp->para[1].ref);
         pobj = new vector<ND::TTruthVerticesModule::TTruthVertex*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthVerticesModule::TTruthVertex*>* pobj;
         const vector<ND::TTruthVerticesModule::TTruthVertex*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetVerticesByTime((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
         pobj = new vector<ND::TTruthVerticesModule::TTruthVertex*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthVerticesModule::TTruthVertex*>* pobj;
         const vector<ND::TTruthVerticesModule::TTruthVertex*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetVerticesByNeutrinoPDG((Int_t) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthVerticesModule::TTruthVertex*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthVerticesModule::TTruthVertex*>* pobj;
         const vector<ND::TTruthVerticesModule::TTruthVertex*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetVerticesByTargetPDG((Int_t) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthVerticesModule::TTruthVertex*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthVerticesModule::TTruthVertex*>* pobj;
         const vector<ND::TTruthVerticesModule::TTruthVertex*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetVerticesBySubdetector((int) G__int(libp->para[0]));
         pobj = new vector<ND::TTruthVerticesModule::TTruthVertex*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G_TTruthUtils_691_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<ND::TTruthVerticesModule::TTruthVertex*>* pobj;
         const vector<ND::TTruthVerticesModule::TTruthVertex*> xobj = ((const TTruthUtils*) G__getstructoffset())->GetVerticesVector();
         pobj = new vector<ND::TTruthVerticesModule::TTruthVertex*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G_TTruthUtils_691_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TTruthUtils* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TTruthUtils(*(TTruthUtils*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TTruthUtils G__TTTruthUtils;
static int G__G_TTruthUtils_691_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TTruthUtils*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TTruthUtils*) (soff+(sizeof(TTruthUtils)*i)))->~G__TTTruthUtils();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TTruthUtils*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TTruthUtils*) (soff))->~G__TTTruthUtils();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G_TTruthUtils_691_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TTruthUtils* dest = (TTruthUtils*) G__getstructoffset();
   *dest = *(TTruthUtils*) libp->para[0].ref;
   const TTruthUtils& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TTruthUtils */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG_TTruthUtils {
 public:
  G__Sizep2memfuncG_TTruthUtils(): p(&G__Sizep2memfuncG_TTruthUtils::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG_TTruthUtils::*p)();
};

size_t G__get_sizep2memfuncG_TTruthUtils()
{
  G__Sizep2memfuncG_TTruthUtils a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG_TTruthUtils() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG_TTruthUtils() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ND::TDatum*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,TGeoElementRN*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*,less<int> >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ThreadData_t*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGeoVolumeAssembly::ThreadData_t*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,std::pair<int,const TGeoNode*> >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_maplEintcOpairlEintcOconstsPTGeoNodemUgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlEintcOconstsPTGeoNodemUgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,pair<int,const TGeoNode*> >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_maplEintcOpairlEintcOconstsPTGeoNodemUgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlEintcOconstsPTGeoNodemUgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,pair<int,const TGeoNode*>,less<int> >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_maplEintcOpairlEintcOconstsPTGeoNodemUgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlEintcOconstsPTGeoNodemUgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVector3*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVector3mUcOallocatorlETVector3mUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3mUcOallocatorlETVector3mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVector3mUcOallocatorlETVector3mUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3mUcOallocatorlETVector3mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVector3mUcOallocatorlETVector3mUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TLorentzVector*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVector3>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVector3cOallocatorlETVector3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVector3cOallocatorlETVector3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETVector3cOallocatorlETVector3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<int,TVector2> >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<float> >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<float,allocator<float> > >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<short> >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<short,allocator<short> > >",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ND::TTruthTrajectoriesModule::TTruthTrajectoryPoint>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TLorentzVector>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ND::TTruthVerticesModule::TTruthVertex*>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TTruthUtils */
static void G__setup_memvarTTruthUtils(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils));
   { TTruthUtils *p; p=(TTruthUtils*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TClonesArray),-1,-1,4,"fTrajectories=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G_TTruthUtilsLN_TClonesArray),-1,-1,4,"fVertices=",0,(char*)NULL);
   G__memvar_setup((void*)0,73,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNTrajectories=",0,(char*)NULL);
   G__memvar_setup((void*)0,73,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNVertices=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"verbosity=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fOrdered=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG_TTruthUtils() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTTruthUtils(void) {
   /* TTruthUtils */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils));
   G__memfunc_setup("TTruthUtils",1148,G__G_TTruthUtils_691_0_1, 105, G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils), -1, 0, 4, 1, 1, 0, 
"U 'TClonesArray' - 0 - trajectories U 'TClonesArray' - 0 - vertices "
"I - 'Int_t' 0 - n_trajectories I - 'Int_t' 0 - n_vertices", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TTruthUtils",1148,G__G_TTruthUtils_691_0_2, 105, G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetVerticesArray",1648,G__G_TTruthUtils_691_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TClonesArray' - 0 - vertices", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetVerticesNumber",1754,G__G_TTruthUtils_691_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "I - 'Int_t' 0 - n_vertices", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTrajectoriesArray",2074,G__G_TTruthUtils_691_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TClonesArray' - 0 - trajectories", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTrajectoriesNumber",2180,G__G_TTruthUtils_691_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "I - 'Int_t' 0 - n_trajectories", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoryById",1711,G__G_TTruthUtils_691_0_7, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory), -1, 0, 1, 1, 1, 8, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParentTrajectory",1969,G__G_TTruthUtils_691_0_8, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory), -1, 0, 1, 1, 1, 8, "i - 'Int_t' 0 - child_id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParentTrajectory",1969,G__G_TTruthUtils_691_0_9, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory), -1, 0, 1, 1, 1, 8, "U 'ND::TTruthTrajectoriesModule::TTruthTrajectory' - 0 - child_trajectory", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPrimaryParentTrajectory",2709,G__G_TTruthUtils_691_0_10, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory), -1, 0, 1, 1, 1, 8, "i - 'Int_t' 0 - child_id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPrimaryParentTrajectory",2709,G__G_TTruthUtils_691_0_11, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory), -1, 0, 1, 1, 1, 8, "U 'ND::TTruthTrajectoriesModule::TTruthTrajectory' - 0 - child_trajectory", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMomentumSortedTrajectories",3026,G__G_TTruthUtils_691_0_12, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoriesByCategory",2568,G__G_TTruthUtils_691_0_13, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 1, 1, 1, 8, "i - - 0 - category", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoriesByName",2123,G__G_TTruthUtils_691_0_14, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 1, 1, 1, 8, "u 'string' - 0 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoriesByPDG",1957,G__G_TTruthUtils_691_0_15, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - pdg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoriesByParent",2356,G__G_TTruthUtils_691_0_16, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - parent_id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoriesByParent",2356,G__G_TTruthUtils_691_0_17, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 1, 1, 1, 8, "U 'ND::TTruthTrajectoriesModule::TTruthTrajectory' - 0 - parent", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoriesByPrimaryParent",3096,G__G_TTruthUtils_691_0_18, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - primary_parent_id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoriesByPrimaryParent",3096,G__G_TTruthUtils_691_0_19, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 1, 1, 1, 8, "U 'ND::TTruthTrajectoriesModule::TTruthTrajectory' - 0 - primary_parent", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrajectoriesVector",2178,G__G_TTruthUtils_691_0_20, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR), G__defined_typename("vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*>"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVertexById",1286,G__G_TTruthUtils_691_0_21, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModulecLcLTTruthVertex), -1, 0, 1, 1, 1, 8, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVertexOfTrajectory",2170,G__G_TTruthUtils_691_0_22, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModulecLcLTTruthVertex), -1, 0, 1, 1, 1, 8, "i - 'Int_t' 0 - trajectory_id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVertexOfTrajectory",2170,G__G_TTruthUtils_691_0_23, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModulecLcLTTruthVertex), -1, 0, 1, 1, 1, 8, "U 'ND::TTruthTrajectoriesModule::TTruthTrajectory' - 0 - trajectory", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVertexOfPrimaryTrajectory",2910,G__G_TTruthUtils_691_0_24, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModulecLcLTTruthVertex), -1, 0, 1, 1, 1, 8, "i - 'Int_t' 0 - primary_trajectory_id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVertexOfPrimaryTrajectory",2910,G__G_TTruthUtils_691_0_25, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModulecLcLTTruthVertex), -1, 0, 1, 1, 1, 8, "U 'ND::TTruthTrajectoriesModule::TTruthTrajectory' - 0 - primary_trajectory", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVerticesByLocation",2137,G__G_TTruthUtils_691_0_26, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR), G__defined_typename("vector<ND::TTruthVerticesModule::TTruthVertex*>"), 0, 2, 1, 1, 8, 
"u 'TVector3' - 11 - min_corner u 'TVector3' - 11 - max_corner", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVerticesByTime",1711,G__G_TTruthUtils_691_0_27, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR), G__defined_typename("vector<ND::TTruthVerticesModule::TTruthVertex*>"), 0, 2, 1, 1, 8, 
"d - 'Double_t' 0 - min_time d - 'Double_t' 0 - max_time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVerticesByNeutrinoPDG",2383,G__G_TTruthUtils_691_0_28, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR), G__defined_typename("vector<ND::TTruthVerticesModule::TTruthVertex*>"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - neutrino_pdg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVerticesByTargetPDG",2146,G__G_TTruthUtils_691_0_29, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR), G__defined_typename("vector<ND::TTruthVerticesModule::TTruthVertex*>"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - target_pdg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVerticesBySubdetector",2468,G__G_TTruthUtils_691_0_30, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR), G__defined_typename("vector<ND::TTruthVerticesModule::TTruthVertex*>"), 0, 1, 1, 1, 8, "i - - 0 - subdetector", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVerticesVector",1752,G__G_TTruthUtils_691_0_31, 117, G__get_linked_tagnum(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR), G__defined_typename("vector<ND::TTruthVerticesModule::TTruthVertex*>"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BinaryTrajectorySearch",2274,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory), -1, 0, 3, 1, 4, 8, 
"i - 'Int_t' 0 - id i - 'Int_t' 0 '0' low "
"i - 'Int_t' 0 '-1' high", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindTrajectorySlowly",2098,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory), -1, 0, 1, 1, 4, 8, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CheckTrajectoryOrdering",2367,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("TTruthUtils", 1148, G__G_TTruthUtils_691_0_35, (int) ('i'), G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils), -1, 0, 1, 1, 1, 0, "u 'TTruthUtils' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TTruthUtils", 1274, G__G_TTruthUtils_691_0_36, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G_TTruthUtils_691_0_37, (int) ('u'), G__get_linked_tagnum(&G__G_TTruthUtilsLN_TTruthUtils), -1, 1, 1, 1, 1, 0, "u 'TTruthUtils' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG_TTruthUtils() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG_TTruthUtils() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG_TTruthUtils() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G_TTruthUtilsLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_ND = { "ND" , 110 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgR = { "vector<ND::TDatum*,allocator<ND::TDatum*> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ND::TDatum*,allocator<ND::TDatum*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR = { "map<int,TGeoElementRN*,less<int>,allocator<pair<const int,TGeoElementRN*> > >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR = { "vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_maplEintcOpairlEintcOconstsPTGeoNodemUgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlEintcOconstsPTGeoNodemUgRsPgRsPgRsPgR = { "map<int,pair<int,const TGeoNode*>,less<int>,allocator<pair<const int,pair<int,const TGeoNode*> > > >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlETVector3mUcOallocatorlETVector3mUgRsPgR = { "vector<TVector3*,allocator<TVector3*> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3mUcOallocatorlETVector3mUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVector3*,allocator<TVector3*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgR = { "vector<TLorentzVector*,allocator<TLorentzVector*> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLorentzVector*,allocator<TLorentzVector*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlETVector3cOallocatorlETVector3gRsPgR = { "vector<TVector3,allocator<TVector3> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVector3,allocator<TVector3> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgR = { "vector<pair<int,TVector2>,allocator<pair<int,TVector2> > >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<int,TVector2>,allocator<pair<int,TVector2> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR = { "vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR = { "vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModule = { "ND::TTruthVerticesModule" , 110 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModulecLcLTTruthVertex = { "ND::TTruthVerticesModule::TTruthVertex" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModule = { "ND::TTruthTrajectoriesModule" , 110 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory = { "ND::TTruthTrajectoriesModule::TTruthTrajectory" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgR = { "vector<ND::TTruthTrajectoriesModule::TTruthTrajectoryPoint,allocator<ND::TTruthTrajectoriesModule::TTruthTrajectoryPoint> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ND::TTruthTrajectoriesModule::TTruthTrajectoryPoint,allocator<ND::TTruthTrajectoriesModule::TTruthTrajectoryPoint> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR = { "vector<TLorentzVector,allocator<TLorentzVector> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLorentzVector,allocator<TLorentzVector> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_TTruthUtils = { "TTruthUtils" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR = { "vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*,allocator<ND::TTruthTrajectoriesModule::TTruthTrajectory*> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ND::TTruthTrajectoriesModule::TTruthTrajectory*,allocator<ND::TTruthTrajectoriesModule::TTruthTrajectory*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR = { "vector<ND::TTruthVerticesModule::TTruthVertex*,allocator<ND::TTruthVerticesModule::TTruthVertex*> >" , 99 , -1 };
G__linked_taginfo G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ND::TTruthVerticesModule::TTruthVertex*,allocator<ND::TTruthVerticesModule::TTruthVertex*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG_TTruthUtils() {
  G__G_TTruthUtilsLN_string.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TClonesArray.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_ND.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TVector3.tagnum = -1 ;
  G__G_TTruthUtilsLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_maplEintcOpairlEintcOconstsPTGeoNodemUgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlEintcOconstsPTGeoNodemUgRsPgRsPgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlETVector3mUcOallocatorlETVector3mUgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3mUcOallocatorlETVector3mUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlETVector3cOallocatorlETVector3gRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModule.tagnum = -1 ;
  G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModulecLcLTTruthVertex.tagnum = -1 ;
  G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModule.tagnum = -1 ;
  G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_TTruthUtils.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR.tagnum = -1 ;
  G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG_TTruthUtils() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_string);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_ND);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTDatummUcOallocatorlENDcLcLTDatummUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TVector3);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_maplEintcOpairlEintcOconstsPTGeoNodemUgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOpairlEintcOconstsPTGeoNodemUgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlETVector3mUcOallocatorlETVector3mUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3mUcOallocatorlETVector3mUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectormUcOallocatorlETLorentzVectormUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlETVector3cOallocatorlETVector3gRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEpairlEintcOTVector2gRcOallocatorlEpairlEintcOTVector2gRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModule);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_NDcLcLTTruthVerticesModulecLcLTTruthVertex);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModule);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_NDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectory);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectoryPointgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_TTruthUtils),sizeof(TTruthUtils),-1,296192,(char*)NULL,G__setup_memvarTTruthUtils,G__setup_memfuncTTruthUtils);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUcOallocatorlENDcLcLTTruthTrajectoriesModulecLcLTTruthTrajectorymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_vectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G_TTruthUtilsLN_reverse_iteratorlEvectorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUcOallocatorlENDcLcLTTruthVerticesModulecLcLTTruthVertexmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupG_TTruthUtils(void) {
  G__check_setup_version(30051515,"G__cpp_setupG_TTruthUtils()");
  G__set_cpp_environmentG_TTruthUtils();
  G__cpp_setup_tagtableG_TTruthUtils();

  G__cpp_setup_inheritanceG_TTruthUtils();

  G__cpp_setup_typetableG_TTruthUtils();

  G__cpp_setup_memvarG_TTruthUtils();

  G__cpp_setup_memfuncG_TTruthUtils();
  G__cpp_setup_globalG_TTruthUtils();
  G__cpp_setup_funcG_TTruthUtils();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG_TTruthUtils();
  return;
}
class G__cpp_setup_initG_TTruthUtils {
  public:
    G__cpp_setup_initG_TTruthUtils() { G__add_setup_func("G_TTruthUtils",(G__incsetup)(&G__cpp_setupG_TTruthUtils)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG_TTruthUtils() { G__remove_setup_func("G_TTruthUtils"); }
};
G__cpp_setup_initG_TTruthUtils G__cpp_setup_initializerG_TTruthUtils;

