//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jan 20 12:54:43 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file test_ev_anal.root
//////////////////////////////////////////////////////////


#ifndef ND__TSHAHashValue_h
#define ND__TSHAHashValue_h
namespace ND {
class TSHAHashValue;
} // end of namespace.

#include "TNamed.h"

namespace ND {
class TSHAHashValue {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fHash[5];    //

   TSHAHashValue();
   TSHAHashValue(const TSHAHashValue & );
   virtual ~TSHAHashValue();

};
} // namespace
#endif
