//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jan 20 12:54:43 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file test_ev_anal.root
//////////////////////////////////////////////////////////


#ifndef ND__TP0DReconModule__TP0DParticle_h
#define ND__TP0DReconModule__TP0DParticle_h
namespace ND {
namespace TP0DReconModule {
class TP0DParticle;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <string>
#include <vector>
#include "TLorentzVector.h"
#include "TVector3.h"
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace ND {
namespace TP0DReconModule {
class TP0DParticle : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //
   short       Cycle;            ///< The cycle number, based on the first hit.
   vector<short> Vertices;         //
   vector<short> Particles;        //
   vector<short> Tracks;           //
   vector<short> Showers;          //
   vector<short> Clusters;         //
   vector<short> Nodes;            //
   vector<short> Hits;             //
   short         NHits;            ///< A count of the Hits associated with this object.
   UInt_t        UniqueID;         //
   int           Status;           //
   float         Quality;          //
   int           NDOF;             //
   vector<int>   Truth_PrimaryTrajIDs;    //
   vector<int>   Truth_TrajIDs;           //
   vector<short> Truth_HitCount;          //
   vector<float> Truth_ChargeShare;       //
   float         SideDeposit;             //
   float         EndDeposit;              //
   TLorentzVector Position;                //
   TLorentzVector PosVariance;             //
   short          ValidDimensions;         //
   TVector3       Direction;               //
   TVector3       DirVariance;             //
   float          Momentum;                //
   float          Charge;                  ///< The reconstructed charge of the corresponding TReconPID.
   vector<string> realPIDNames;            //
   vector<vector<float> > realPIDValues;           //
   vector<string>         integerPIDNames;         //
   vector<vector<short> > integerPIDValues;        //
   vector<short>          PID;                     //
   vector<float>          PID_weight;              //

   TP0DParticle();
   TP0DParticle(const TP0DParticle & );
   virtual ~TP0DParticle();

   ClassDef(TP0DParticle,6); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
