//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jan 20 12:54:43 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file test_ev_anal.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALReconModule__TECALReconCluster_h
#define ND__TTrackerECALReconModule__TECALReconCluster_h
namespace ND {
namespace TTrackerECALReconModule {
class TECALReconCluster;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TLorentzVector.h"

namespace ND {
namespace TTrackerECALReconModule {
class TECALReconCluster : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //
   TLorentzVector PositionVar;    //
   int            NDOF;           //
   double         EDeposit;       //

   TECALReconCluster();
   TECALReconCluster(const TECALReconCluster & );
   virtual ~TECALReconCluster();

   ClassDef(TECALReconCluster,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
