//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jan 20 12:54:43 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file test_ev_anal.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TGlobalVertex_h
#define ND__TGlobalReconModule__TGlobalVertex_h
namespace ND {
namespace TGlobalReconModule {
class TGlobalVertex;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"
#include "TClonesArray.h"
#include "ND__TTrueVertex.h"
#include "ND__TGlobalReconModule__TVertexConstituent.h"

namespace ND {
namespace TGlobalReconModule {
class TGlobalVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         PrimaryIndex;    //
   string      AlgorithmName;    //
   int         Status;           //
   double      Quality;          //
   int         NDOF;             //
   TLorentzVector Position;         //
   TLorentzVector Variance;         //
   Int_t          NTrueVertices;    //
   TClonesArray*  TrueVertices;     //
   Int_t          NConstituents;    //
   TClonesArray*  Constituents;     //
   ND::TTrueVertex hackTrueVertexObject;    //
   ND::TGlobalReconModule::TVertexConstituent hackVertexConstituentObject;    //

   TGlobalVertex();
   TGlobalVertex(const TGlobalVertex & );
   virtual ~TGlobalVertex();

   ClassDef(TGlobalVertex,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
