//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jan 20 12:54:43 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file test_ev_anal.root
//////////////////////////////////////////////////////////


#ifndef ND__TFgdOnlyModule__TFgd3DShowerHyp_h
#define ND__TFgdOnlyModule__TFgd3DShowerHyp_h
namespace ND {
namespace TFgdOnlyModule {
class TFgd3DShowerHyp;
} // end of namespace.
} // end of namespace.

#include "TObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"

namespace ND {
namespace TFgdOnlyModule {
class TFgd3DShowerHyp : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    ///< Identified start position of the shower.
   TLorentzVector PositionVar;    ///< Variance on the start position of the shower.
   TVector3       Direction;      ///< Identified direction of the shower, found using PCA.
   TVector3       DirectionVar;    ///< Variance on the direction of the shower.
   TVector3       ConeAngle;       ///< Opening angle of the cone describing this shower.
   TVector3       ConeAngleVar;    ///< Variance on the cone opening angle.
   double         EDeposit;        ///< Energy deposited in this shower.
   TVector3       QAvgInThirds;    //Charge of hits in 1st, 2nd and 3rd groups, based
   TVector3       SpreadInThirds;    //Average transverse spread of hits  in the 1st,

   TFgd3DShowerHyp();
   TFgd3DShowerHyp(const TFgd3DShowerHyp & );
   virtual ~TFgd3DShowerHyp();

   ClassDef(TFgd3DShowerHyp,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
