//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jan 20 12:54:43 2017 by ROOT version 5.34/34)
//      from the StreamerInfo in file test_ev_anal.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TTrackerObject_h
#define ND__TGlobalReconModule__TTrackerObject_h
namespace ND {
namespace TGlobalReconModule {
class TTrackerObject;
} // end of namespace.
} // end of namespace.

#include "ND__TSubBaseObject.h"

namespace ND {
namespace TGlobalReconModule {
class TTrackerObject : public ND::TSubBaseObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      Charge;      //
   int         matchingFailure_flag;    //

   TTrackerObject();
   TTrackerObject(const TTrackerObject & );
   virtual ~TTrackerObject();

   ClassDef(TTrackerObject,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
