/********************************************************************
* /home/t2k/aspeers/Highland_Installs/HighLAND_2.89/psycheND280Utils_3.73/Linux-CentOS_7-gcc_4.8-x86_64/dict/G_FiducialVolumeDefinition.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/t2k/aspeers/Highland_Installs/HighLAND_2.89/psycheND280Utils_3.73/Linux-CentOS_7-gcc_4.8-x86_64/dict/G_FiducialVolumeDefinition.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG_FiducialVolumeDefinition();
extern void G__cpp_setup_inheritanceG_FiducialVolumeDefinition();
extern void G__cpp_setup_typetableG_FiducialVolumeDefinition();
extern void G__cpp_setup_memvarG_FiducialVolumeDefinition();
extern void G__cpp_setup_globalG_FiducialVolumeDefinition();
extern void G__cpp_setup_memfuncG_FiducialVolumeDefinition();
extern void G__cpp_setup_funcG_FiducialVolumeDefinition();
extern void G__set_cpp_environmentG_FiducialVolumeDefinition();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/t2k/aspeers/Highland_Installs/HighLAND_2.89/psycheND280Utils_3.73/inc/FiducialVolumeDefinition.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G_FiducialVolumeDefinitionLN_FVDef;

/* STUB derived class for protected member access */
