//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Nov  9 15:39:21 2016 by ROOT version 5.34/09)
//      from the StreamerInfo in file /Users/izmaylov/Downloads/oa_nt_beam_90210000-0000_2e7lhce5kvor_anal_000_prod6amagnet201011waterb-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TBasicDataQualityModule_h
#define ND__TBasicDataQualityModule_h
namespace ND {
class TBasicDataQualityModule;
} // end of namespace.

#include "ND__TAnalysisHeaderModuleBase.h"

namespace ND {
class TBasicDataQualityModule : public ND::TAnalysisHeaderModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TBasicDataQualityModule();
   TBasicDataQualityModule(const TBasicDataQualityModule & );
   virtual ~TBasicDataQualityModule();

   ClassDef(TBasicDataQualityModule,2); // Generated by MakeProject.
};
} // namespace
#endif
