//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Nov  9 15:39:20 2016 by ROOT version 5.34/09)
//      from the StreamerInfo in file /Users/izmaylov/Downloads/oa_nt_beam_90210000-0000_2e7lhce5kvor_anal_000_prod6amagnet201011waterb-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TData_h
#define ND__TData_h
namespace ND {
class TData;
} // end of namespace.

#include "ND__TDatum.h"

namespace ND {
class TData : public ND::TDatum {

public:
// Nested classes declaration.

public:
// Data Members.

   TData();
   TData(const TData & );
   virtual ~TData();

   ClassDef(TData,4); // Generated by MakeProject.
};
} // namespace
#endif
