#ifndef ANATOOLS_FILE_VERSION
#define ANATOOLS_FILE_VERSION v11r31p9
#define ANATOOLS_FILE_MAJOR_VERSION 11
#define ANATOOLS_FILE_MINOR_VERSION 31
#define ANATOOLS_FILE_PATCH_VERSION 9
#define BEFORE_ANATOOLS_FILE(v,r,p) ((ANATOOLS_FILE_MAJOR_VERSION==(v)&&ANATOOLS_FILE_MINOR_VERSION==(r)&&ANATOOLS_FILE_PATCH_VERSION<(p))||(ANATOOLS_FILE_MAJOR_VERSION==(v)&&ANATOOLS_FILE_MINOR_VERSION<(r))||(ANATOOLS_FILE_MAJOR_VERSION<(v)))
#define EQUALS_ANATOOLS_FILE(v,r,p) (ANATOOLS_FILE_MAJOR_VERSION==(v)&&ANATOOLS_FILE_MINOR_VERSION==(r)&&ANATOOLS_FILE_PATCH_VERSION==(p))
#define ANATOOLS_FILE_PROD5 BEFORE_ANATOOLS_FILE(11,0,0)
#define ANATOOLS_FILE_AFTERPROD5 !BEFORE_ANATOOLS_FILE(11,0,0)
#endif
