//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Jul 15 17:55:45 2022 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_90400072-0007_ok762udcurva_anal_000_magnet201011airrun4-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__ToaAnalysisUtils_h
#define ND__ToaAnalysisUtils_h
namespace ND {
class ToaAnalysisUtils;
} // end of namespace.

#include "TObject.h"

namespace ND {
class ToaAnalysisUtils : public TObject {

public:
// Nested classes forward declaration.
enum EParticleCategory { kDefault_EParticleCategory };
enum ESubdetector { kDefault_ESubdetector };

public:
// Nested classes declaration.

public:
// Data Members.

   ToaAnalysisUtils();
   ToaAnalysisUtils(const ToaAnalysisUtils & );
   virtual ~ToaAnalysisUtils();

   ClassDef(ToaAnalysisUtils,2); // Generated by MakeProject.
};
} // namespace
#endif
