//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Nov 23 12:47:33 2018 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../../../../Files/Prod6/RQS/oa_nt_beam_80510000-0000_leokxyiuc2jb_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__RooTrackerVtxBase_h
#define ND__RooTrackerVtxBase_h
namespace ND {
class RooTrackerVtxBase;
} // end of namespace.

#include "TObject.h"

namespace ND {
class RooTrackerVtxBase : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.

   RooTrackerVtxBase();
   RooTrackerVtxBase(const RooTrackerVtxBase & );
   virtual ~RooTrackerVtxBase();

   ClassDef(RooTrackerVtxBase,2); // Generated by MakeProject.
};
} // namespace
#endif
