//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Jul 27 10:02:44 2022 by ROOT version 5.34/34)
//      from the StreamerInfo in file ../../oa_nt_beam_80710040-0003_c37su7dkqshx_anal_000_nu-bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ROOT__TIOFeatures_h
#define ROOT__TIOFeatures_h
namespace ROOT {
class TIOFeatures;
} // end of namespace.

#include "TNamed.h"

namespace ROOT {
class TIOFeatures {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned char fIOBits;     //

   TIOFeatures();
   TIOFeatures(const TIOFeatures & );
   virtual ~TIOFeatures();

};
} // namespace
#endif
